name: amphawan
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  ff_navigation_bar: ^0.0.1
  http: ^0.12.0+2
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: '79ff08a'
  flutter_line_sdk: ^1.3.0
  #---------------
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bg/bg.png
    - assets/images/information/amphawan.png
    - assets/images/information/amphawan-1.png 
    ##LOGO
    - assets/images/logo/facebook.png
    - assets/images/logo/line.png
    - assets/images/logo/google.png
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Kanit
       fonts:
        - asset: assets/fonts/Kanit-Black.ttf
        - asset: assets/fonts/Kanit-BlackItalic.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
        - asset: assets/fonts/Kanit-BoldItalic.ttf
        - asset: assets/fonts/Kanit-ExtraBold.ttf 
        - asset: assets/fonts/Kanit-ExtraBoldItalic.ttf
        - asset: assets/fonts/Kanit-ExtraLight.ttf
        - asset: assets/fonts/Kanit-ExtraLightItalic.ttf
        - asset: assets/fonts/Kanit-Italic.ttf
        - asset: assets/fonts/Kanit-Light.ttf
        - asset: assets/fonts/Kanit-LightItalic.ttf
        - asset: assets/fonts/Kanit-Medium.ttf
        - asset: assets/fonts/Kanit-MediumItalic.ttf
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-SemiBold.ttf
        - asset: assets/fonts/Kanit-SemiBoldItalic.ttf
        - asset: assets/fonts/Kanit-Thin.ttf
        - asset: assets/fonts/Kanit-ThinItalic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
